blank_issues_enabled: false
contact_links:
  - name: Votre problème concerne une faille de sécurité ?
    url: https://github.com/PapillonApp/Papillon/security/advisories/
    about: Merci de nous contacter via ce formulaire.
  - name: Vous avez un problème personnel ?
    url: https://discord.gg/WXntBawAk8
    about: Merci de nous contacter via notre serveur Discord.
  - name: Vous avez une question ?
    url: https://discord.gg/WXntBawAk8
    about: Merci de nous contacter via notre serveur Discord.