on: [push]
jobs:
  react_native_ci_job:
    runs-on: ubuntu-latest
    name: React Native CI Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: React Native CI
        uses: aslamanver/react-native-docker@v1
      - name: Install NPM Dependencies
        run: npm install
      - name: Run Android Build
        run: npx nx build-android mobile
